#!/usr/bin/env bash

HIGH_TEMP=""
LOW_TEMP=""

TEMP=$(echo "scale=1; $(sensors | grep Core | awk '{print $3}' | cut -b 2- | cut -b -4 | paste -sd+ - | bc)/$(nproc)" | bc -l)


if [[ $TEMP > 60 ]]; then
        echo "$HIGH_TEMP $TEMP°C"
else
        echo "$LOW_TEMP $TEMP°C"
fi

# Implement the click actions
case $BUTTON in
        6) st -e vim $(which $0) ;;
esac

